### ISSUE TITLE
Start world: in the airport where the user aircraft is located

### ISSUE THREAD

**Issue by felix-b** [felix-b/atc#184]
Currently, it's hard-coded KJFK. 
Required: the airport where the user aircraft is located when Start World or Reset World menu option is selected.

**Comment by togfoxy** [comment]
You probably know this but XPLANE has the following native function:

navref = XPLMFindNavAid( nil, nil, LATITUDE, LONGITUDE, nil, xplm_Nav_Airport)

Latitude and Longitude is for the player. Plug that in and you get an ICAO code back. Hope that helps.

**Comment by felix-b** [comment]
Cool! I was going to look for it 👍 thank you

**Comment by felix-b** [comment]
@togfoxy 

I'm wondering if/how I should implement data layering as described here: https://developer.x-plane.com/?article=navdata-in-x-plane-11

As far as I understand, most of those layers don't apply to **apt.dat**. But I do find **apt.dat** in custom scenery airports. 

The thing is, that default **apt.dat** often has more data on an airport than the custom one. On the other hand, custom **apt.dat** often has small differences in lat/lon compared to default (e.g. 27.40893724 vs 27.40917649), so I guess custom **apt.dat** better matches the custom scenery. 

For now I'll start from reading the default **apt.dat**. 
WDYT?

**Comment by felix-b** [comment]
Let's define a list of 10 must "important" airports to test the plugin on.
- KJFK
- KMIA
- .... (7 more airports outside of US?)
- KORD (a feat...)

**Comment by felix-b** [comment]
(reposted on behalf of @togfoxy)

Suggested types of test airports:
2 parallel runways
2 intersecting runways
1 runway
Ramps is different types (tie down/gate etc)
Ramps with different operations (military/GA etc
Taxi network with different complexities.
I could easily find a mixed bag for testing purposes.

**Comment by felix-b** [comment]
> I do this frequently to align with ortho images
so it can be a noticeable misalignment - a good reason for loading custom apt.dat

but what about custom apt.dat missing some data that is present in default apt.dat, like taxiways? 
from your experience, is there a trend that default airports (the WED/Gateway ones) have better quality data than custom ones?

**Comment by togfoxy** [comment]
You can start with default apt as an experiment/learning thing but ultimately the custom apt will be required because that's what the pilot sees and that that's where the runway and taxi's are. You won't want ground traffic driving about where the taxi USE to be. You could take the view that many custom apt's are submitted to the gateway and eventually become the default apt but again, in many cases, custom airports are not submitted or don't qualify for the gateway.

Custom apt is nearly always better than default. Custom apt exists because and only because some designer has determined the default apt is substandard in some way. The improvement offered in the custom apt can be a little (taxi's re-aligned) to a lot (complete scenery make-over).

As to why a custom apt is 'thinner' than default is not clear to me. I'm guessing - and only guessing - the full set of apt data consists of default apt + custom apt over-writing parts of default. In other words - and only a guess - that custom apt does not contain the full set of data. I hope not. That would be programmatically frustrating.  :(

I can do some experimenting in WED and apt files to see what I can uncover. APT files are text based so this is something I should be able to do with the tools I have (notepad++ & WED & sim).

**Comment by togfoxy** [comment]
Noting here for reference and later recall: https://developer.x-plane.com/article/airport-data-apt-dat-file-format-specification/

**Comment by felix-b** [comment]
>  I'm guessing - and only guessing - the full set of apt data consists of default apt + custom apt over-writing parts of default

I hope it doesn't. I thought about combining the two by myself - but then I realized that it isn't safe - the merged version can have inconsistencies between its parts.

As the first step, I'm reading just the default apt.dat. 
Next, fix the most severe quirks at different airports
Then, add loading of custom apt.dat
WDYT?

**Comment by felix-b** [comment]
Meanwhile, it already works on my machine, and of course - I'm spotting quirks at different airports. 

Most important issues I've spotted by far:

#### Issue 1: Loading the entire apt.dat takes 20-30 seconds, during which the sim is frozen after clicking "Start World". 

Possible solutions:
    - (A) - easiest: Unfreeze the sim and load in the background - the user can play but traffic/ATC will start after 20-30 seconds
    - (B) - relatively easy: Start loading while the user is still at the holodeck. By the time he/she gets to the flight, it should be ready
    - (C) - hardest: Preload once and cache in a file - hopefully, load from the cache will take 1-2 seconds. I plan this cache to include all of the nav data. It's quite a serious programming effort - but we will need this mechanism anyway for the long term.  (will create a separate issue for that)

I would go for (B) because this "pre-initialization" phase will be required in any way. And it's too early for (C) - although we will have to do (C) at the right timing, because it's gonna be 1-2 weeks of work.

#### Issue 2: We don't seem to have the correct ATC call signs anywhere in the data

The "Kennedy Tower" was hard-coded. This is what we have in apt.dat:
```
1052 135050 CLNC DEL
1053 125050 GND
1054 119100 KENNEDY TWR
1055 123700 NEW YORK APP
1056 123700 NEW YORK DEP
```
sometimes it looks like this:
```
1055 124550 JOSHUA APP CON
1056 124550 JOSHUA DEP CON
1054 118350 VICTORVILLE TOWER
1053 124450 VICTORVILLE GND CON
```
but sometimes it's just:
```
1052 124250 CLNC DEL
1053 121700 GND
1054 128150 TWR
```
Prefixing the name of the airport won't work ("John F Kennedy Intl Tower" - sounds bad)
For now I'm doing ICAO_CODE + POSITION, like "KJFK Tower" - of course it's a patch
It seems we'll need manually configured overrides, at least for a selected list of airports. But the list can grow with time.
Maybe you have a better idea though

#### Issue 3: Loops in pilot/ATC conversations

Right now we have a simplified pilot/ATC workflow - the proper workflows aren't yet in place, 
The simplified workflow makes assumptions that worked in JFK, but are easily broken in other airports. 
For example, having more than one taxi edge marked as active zone before the runway creates funny loops in conversations.
Example: holding short before lining up at KMIA

**Comment by togfoxy** [comment]
![Untitled](https://user-images.githubusercontent.com/5599266/94407287-a216a200-01b6-11eb-8659-0d6c70eac984.png)

From the spec PDF

**Comment by felix-b** [comment]
Exactly, 
and I have actual examples from global apt.dat - see above.

**Comment by felix-b** [comment]
Closed accidentally - reopening.

**Comment by felix-b** [comment]
Closing as the main work is done. 
Will reopen if it doesn't work or if it has very severe issues.
Otherwise, let's report found issues as either bugs or enhancements.

**Comment by togfoxy** [comment]
It's perfectly legit for ATC to call themselves "Tower".  :)

Speedboat 332, Tower, clear for take off runway 22.

But yes - you have a point - some names in the apt will be cumbersome. I think we just need to let the WED designers lift their game. We can't be expected to compensate for everything in one plugin.

**Comment by felix-b** [comment]
I guess it's OK to define a few patterns that get automatically expanded, and the rest will be just the controller position (Ground/Tower/...).

Examples of patterns:
```
CLNC -> Clearance
CLNC DEL -> Clearance delivery
GND -> Ground
TWR -> Tower
APP -> Approach
DEP -> Departure
CLNC/GND -> split into 2 then read each one separately
APP/DEP -> split into 2 then read each one separately
```
A good example:
```
YUMA APP -> YUMA Approach
```
A not-so-good example (the "BARB" part):
```
SANTA BARB APP/DEP -> SANTA BARB Approach + SANTA BARB Departure
```
A agree that we cannot fix it all, though. 
It can be that mixing in Navigraph data will give better results - when we'll get to that.
