### ISSUE TITLE
A plane that is landed will taxi off the end of the rway and keep going.

### ISSUE THREAD

**Issue by togfoxy** [felix-b/atc#197]
Suggest either:
1) taxi to gate
2) stop the plane on rway and despawn it
or
3) remove landing aircraft for MVP

**Comment by togfoxy** [comment]
YBBN

**Comment by felix-b** [comment]
I prefer to make it taxi to gate, there's a small piece of functionality that's missing

**Comment by togfoxy** [comment]
Would like to leave this one in 'testing' for now.

**Comment by felix-b** [comment]
Sometimes it still happens, usually when I do x10 or x20 time acceleration, and when I choose AI traffic at 100% load.

**Comment by crankywright** [comment]
Tracked in https://github.com/felix-b/atc/issues/253

**Comment by crankywright** [comment]
The other cases are tested and working, so removing from the Kanban.
