### ISSUE TITLE
Xplane crashes on exit of sim

### ISSUE THREAD

**Issue by togfoxy** [felix-b/atc#198]
When exiting the sim (i.e. closing xplane) the sim will CTD. Not a biggy because I was exiting anyway.  :)

**Comment by felix-b** [comment]
Is it consistent? Can you post the Log.txt or like 20 last lines of it?

**Comment by felix-b** [comment]
Should be resolved by #209

**Comment by togfoxy** [comment]
I haven't experienced this lately so will move this out of "testing".
