### ISSUE TITLE
The plugin freezes the sim when loading airports

### ISSUE THREAD

**Issue by felix-b** [felix-b/atc#199]
After clicking "Start World" the sim will freeze for 20 seconds until the plugin finishes loading the airports.
Solution: begin loading the airports while the user is still at the holodeck,

**Comment by felix-b** [comment]
This is a result of implementing #184

**Comment by felix-b** [comment]
Resolved by #207

**Comment by togfoxy** [comment]
I haven't experienced this issue so I'll move it out of "testing".
