### ISSUE TITLE
Have planes spawn at random gates

### ISSUE THREAD

**Issue by togfoxy** [felix-b/atc#200]
I suspect the first X gates are chosen to spawn planes. This needs to be randomised. Would help greatly with immersion - even if they parked and didn't move (but I know they can move).

**Comment by felix-b** [comment]
Implemented in #230.

**Comment by felix-b** [comment]
The user has options to spawn AI traffic with 50%, 70%, or 100% load at the airport.
The load is the percent of "usable" gates that are selected for AI traffic.
The selected gates belong 50/50 to departures/arrivals.
So when the flight starts, half of the selected gates will have AI planes parked planned to depart, and the other half will be empty but allocated to the arrivals.

**Comment by felix-b** [comment]
The labels of AI planes have a new indication on them: (A)=arrival, (D)=departure, (T/A)=trurnaround
