### ISSUE TITLE
Read user's destination and SID from flight plan file (.fms + .fmx)

### ISSUE THREAD

**Issue by togfoxy** [felix-b/atc#215]
Remembering that GA aircraft don't have a FMC.

**Comment by felix-b** [comment]
GA planes GPS and airliners FMC are the same thing from the plugin's perspective.
In any way, it doesn't seem to be feasible to extract SIDs and STARTs currently entered into GPS/FMC. 
So I'm going to read SIDs and STARs from .fms/.fmx flight plan files
From the user's perspective, one has to store the flight plan from GPS/FMC (ppl using simbrief.com and the like download these files first anyways), then select the file through our plugin.

**Comment by crankywright** [comment]
Done
