### ISSUE TITLE
Crossing out of runways 

### ISSUE THREAD

**Issue by Random-Ranger** [felix-b/atc#235]
Seen at KDEN : 
Some taxiways have "active zones" to protect runways but never cross the runway (taxiways WB an probably ED at KDEN)
So when a plane is cleared to cross after holding short of the runway, it is never seen as "crossing" (detected on the runway) nor "vacated" (crossing finished).
The runway is then unavailable for landing and other crossing planes.

**Comment by felix-b** [comment]
Nice catch!
