### ISSUE TITLE
At LFPG, TWR does not clear planes for takeoff

### ISSUE THREAD

**Issue by crankywright** [felix-b/atc#245]
At LFPG, TWR does not clear planes for takeoff. They just pile up at the waiting point of departure runway 08L, waiting for takeoff clearance. I tried it three times, always with the same result. You can see in the picture two planes over each other at the waiting point.

![Screenshot](https://forums.x-plane.org/uploads/monthly_2020_11/lfpg_pile_up.thumb.jpg.7adcc8cf227ea99064e7f7bb817b97df.jpg)

**Comment by Random-Ranger** [comment]
@crankywright @felix-b I've been doing some testing at LFPG while working on #222 and found that the first edge of the active zone at T1 (rwy 08L holding point) is only protected against ILS and not departure so the pilot does not checkin with tower.

I'll push a fix ASAP

**Comment by felix-b** [comment]
Thanks @Random-Ranger !
