### ISSUE TITLE
Re: Is this project dead? 

### ISSUE THREAD

**Issue by elmafioso79** [felix-b/atc#264]

**Comment by felix-b** [comment]
@elmafioso79 
No, it isn't dead - It is Alive!
Unfortunately, recent Covid lockdowns in my country required me to take a break from the development.
Nevertheless, I'm looking forward to getting it back on track ASAP!

In addition, a revisited roadmap for the project was published a week ago: 
https://github.com/felix-b/atc/blob/master/docs/roadmap/atc-roadmap.jpg

**Comment by elmafioso79** [comment]
Thanks for replying. I'm happy to read that it's still alive. Looking forward to the next update.
